context.md
This flips the logic for checking for the admin user.
=> Fix doc typo

translations/zh-CN/README.md, translations/zh-CN/SUMMARY.md, translations/zh-CN/application.md, translations/zh-CN/benchmarks.md, translations/zh-CN/context.md, translations/zh-CN/routing.md
Update docs of chinsese translate😊
=> update docs of chinese

translations/zh-CN/application.md, translations/zh-CN/context.md
=> Add Revocer() and Error().

translations/ko/README.md
I translated README.md of Documentation to Korean.
=> Add korean README.md

translations/zh-CN/README.md, translations/zh-CN/application.md, translations/zh-CN/benchmarks.md, translations/zh-CN/context.md, translations/zh-CN/routing.md
=> update chinese docs

middleware.md
According to @Fenny, I added a document about redirect middleware.
=> doc: Redirects middleware.

translations/pt/README.md
Hi, 
I saw the portuguese translation was machine generated and thought to improve it a little.
If you guys like it, I'd be willing to improve the rest of the translation.
=> Improve portuguese translation of the README

translations/ko/README.md
Hello,
I translated ko/README.md.
Also, I will translate other files soon.
Thanks.
=> Update korean README.md

middleware.md
- change AllowCredentials type & default value
- change ExposeHeaders default value
=> update cors properties

application.md, middleware.md
=> Add Session middleware, update code signatures

README.md
In response to https://github.com/gofiber/fiber/issues/426.
=> Add notice for zero allocation behavior

middleware.md
Fix typo in recover middleware link.
=> Fix typo in recover middleware link.

README.md
Add explainer article to quickly get up to speed with Fiber
=> add explainer article for Fiber

templates.md
Attempt to write templates documentation
=> Templates documentation

README.md
=> fix parentheses

middleware.md
I've added a short section to the middleware docs that details how you can skip middleware execution. I've just edited it with a text editor, so if the GitBook syntax is a bit weird, my bad.
=> Add info about skipping middleware

app.md
=> Correct Mount Docs! to be more Clear!

validation.md
validate was not initialized properly
ValidateStruct was missing the pointer to the user struct
=> Validator missing arguments

guide/error-handling.md
Fiber instance was missing a comma
=> fixed syntax error

api/app.md
Related to [#1130](https://github.com/gofiber/fiber/pull/1130)
=> 🔥 Feature: Added Next field for app.Static config.

api/middleware/logger.md
In reference to issue #1115 in gofiber/fiber
=> 🔥 Feature: add logger variables to gofiber docs

api/app.md, guide/grouping.md, guide/routing.md, guide/templates.md, original/application.md, original/middleware.md, original/routing.md
📚 Add a fatal error logger for app.Listen methods
📚 Improve grouping guide example
=> 📚 Improve grouping guide example

api/middleware/csrf.md
update docs so that they are true ref https://github.com/gofiber/fiber/pull/1180
=> 📚 Doc: update csrf middleware to match gofiber/fiber#1180

extra/faq.md
Hello! I just created a boilerplate on top of Fiber framework to make a rest api, hope it works for you. Any feedback is welcome!
=> Adding another boilerplate

api/ctx.md
Added documentation for as requested by [this comment](https://github.com/gofiber/fiber/pull/1243#issuecomment-808900292)
=> Add ctx.ParamsInt documentation

guide/routing.md
🚀 new possibility to escape special routing parameters,
which gives the possibility to follow the google api design guide https://cloud.google.com/apis/design/custom_methods
=> 🚀 new possibility to escape special routing parameters

README.md
Signed-off-by: Ján Dráb <jan@drab.name>
=> Fixed links in routing documentation

api/middleware/session.md
Updating docs.
Refs: [#gofiber/fiber/1337](https://github.com/gofiber/fiber/pull/1337)
=> docs(middleware): session

api/ctx.md
Adding documentation for  user-context propagation
=> Context Propagation Documentation

api/middleware/timeout.md
Updating the docs as these weren't updated by https://github.com/gofiber/fiber/pull/1328
=> timeout: update example for initializing handler

guide/templates.md
Add documentation for ViewsLayout
=> Add documentation for ViewsLayout

api/fiber.md
Add additional Config parameters to support https://github.com/gofiber/fiber/pull/1397 feature
=> 🔥 Feature: Add TrustedProxies feature docs

api/fiber.md
https://github.com/gofiber/fiber/pull/1423
=> Add new config fields as per pullrequest

api/fiber.md
Doc for https://github.com/gofiber/fiber/pull/1418
=> Add documentation for AppName

guide/error-handling.md
Fixing grammar in error-handling.md
=> Grammar fix in error-handling.md

api/middleware/logger.md
As requested in [gofiber/fiber#1448](https://github.com/gofiber/fiber/pull/1448#issuecomment-892395647)
Also, I'd like to suggest you to change gofiber/fiber middlewares README.md docs to provide only most basic usage, and link to this documentation, as the other way around is not feasible, as this docs are used to generate https://docs.gofiber.io. You could also require people to create a PR here in order to have their PR accepted in gofiber/fiber, to keep docs updated. This could be done in the GitHub's pull request's template.
Edit: cc @ReneWerner87
=> Update logger middleware doc

api/middleware/skip.md
corollary of gofiber/fiber#1465
=> add documentation for Skip middleware

api/middleware/skip.md
Correct typo in Skip middleware description
=> Minor typo fix

api/app.md, api/ctx.md, extra/faq.md, guide/error-handling.md, original/application.md, original/context.md, original/middleware.md
replaced all missing status codes with fiber status codes consts
=> replaced all missing status codes with fiber status codes consts

api/middleware/logger.md
=> Fix indentation

SUMMARY.md, api/middleware/monitor.md
=> Doc for Monitor middleware  

guide/validation.md
Added missing double-quotes in a code block
=> Typo in a code block

api/ctx.md
=> Correction on SetParserDecoder() Block

api/middleware/logger.md
=> middleware(logger): remove invalid characters

api/ctx.md, api/middleware/logger.md
Docs for https://github.com/gofiber/fiber/pull/1678
=> Tagreqheaders

api/ctx.md, api/fiber.md
For https://github.com/gofiber/fiber/pull/1677
=> 📝docs(add docs of EnablePrintRoutes config):

api/ctx.md
This is for https://github.com/gofiber/fiber/pull/1671
=> :pencil:docs(Ctx): update docs for IsFromLocal

api/app.md
Add docs for https://github.com/gofiber/fiber/pull/1672.
=> Add docs for HandlersCount.

api/app.md
https://github.com/gofiber/fiber/pull/1650
=> Add docs for route naming

api/app.md
Docs for https://github.com/gofiber/fiber/pull/1713
=> Add docs for Route() method.

api/ctx.md
Docs for https://github.com/gofiber/fiber/pull/1721
=> Add reqheaderparser doc

api/fiber.md
https://github.com/gofiber/fiber/pull/1768
=> remove errors method #1768

api/ctx.md
Doc for https://github.com/gofiber/fiber/pull/1750
=> Add documentation for RedirectToRoute and RedirectBack functions

api/app.md
https://github.com/gofiber/fiber/pull/1729
=> Add docs for static-download.

api/ctx.md, guide/hooks.md
Related to https://github.com/gofiber/fiber/pull/2011
=> Add document in Context for ClientHelloInfo

api/middleware/csrf.md
This PR fixes #274 
and is related to goofier/fiber PR [2052](https://github.com/gofiber/fiber/pull/2052) and issue [2051](https://github.com/gofiber/fiber/issues/2051)
=> 📚 [Docs]: update middleware/csrf for custom Extractor

api/ctx.md, api/fiber.md
https://github.com/gofiber/fiber/pull/2003
=> docs for XML.

guide/routing.md
https://github.com/gofiber/fiber/pull/1998
=> docs for constraints.

api/ctx.md
=> docs(api/ctx): fix typo

api/middleware/timeout.md
Timeout middleware document update related with [Fiber PR #2090](https://github.com/gofiber/fiber/pull/2090)
=> update timeout middleware documentation

api/middleware/timeout.md
Fixes https://github.com/gofiber/fiber/issues/2124
=> ✏️ Fix: typos

api/middleware/cache.md
Added no-cache and no-store request directive descriptions.
=> Added description for the PR gofiber/fiber#2159

api/app.md
doc updates for https://github.com/gofiber/fiber/pull/2140
=> doc updates for PR 2140

.gitignore, api/middleware/proxy.md
refer to https://github.com/gofiber/fiber/pull/2117
=> doc: modify proxy doc

api/app.md
refer to https://github.com/gofiber/fiber/pull/2112
=> doc: add GetRoutes method

README.md
related to https://github.com/gofiber/fiber/pull/2172
=> make go 1.16 minimum version

package-lock.json, package.json
=> Bump @easyops-cn/docusaurus-search-local from 0.40.1 to 0.44.4
