context.md
The `Subdomains` method has zero args.
=> Fix doc for subdomains

context.md
Although `go vet` warns about unexported struct field with json tag, I think it would be better if there were some descriptions about that. (Just for golang noobs like me)
=> Some notes about bodyparser

application.md
The link to https://golang.org/pkg/crypto/tls/#Config in the Application page is broken. This PR fixes it.
=> Fix broken link in Application page

middleware.md
In doc was added parameter from config as `Status` but the right way is `StatusCode`
=> fix: small type to use redirect meddleware

context.md
Just add `>` to close the `<p>` tag in c.Format example.
=> Add missing > a the end of c.Format example

middleware.md, translations/ar/middleware.md, translations/cn/middleware.md, translations/de/middleware.md, translations/el/middleware.md, translations/es/middleware.md, translations/fa/middleware.md, translations/fr/middleware.md, translations/gr/middleware.md, translations/he/middleware.md, translations/hu/middleware.md, translations/id/middleware.md, translations/ir/middleware.md, translations/it/middleware.md, translations/ja/middleware.md, translations/jp/middleware.md, translations/ko/middleware.md, translations/kr/middleware.md, translations/pl/middleware.md, translations/pt/middleware.md, translations/ru/middleware.md, translations/tr/middleware.md, translations/vi/middleware.md, translations/zh/middleware.md
#94  Missing some opening parentheses at the import level in the Middleware examples for part the compression and webSocket
=> Fix missing opening parentheses

fiber.md
Some sentences on Fiber page doesn't have trailing dot. To make it
consistent with the others I add some dot at the end of some
sentences.
Signed-off-by: Zasda Yusuf Mikail <zasdaym@gmail.com>
=> :pencil: Add dots on Fiber page docs

api/middleware/session.md
Fixed errors:
- use of undeclared `ctx`.
- `fmt.Fprintf` returns 2 variables instead or `error`, so I used the combination of `c.SendString` and `fmt.Sprintf`.
=> Fix broken session middleware example.

api/ctx.md
fix "VS Code show error warning when using the "Ctx.Status" example from docs🐛 #1307"
=> fix "VS Code show error warning when using the "Ctx.Status" example from docs🐛 #1307"

api/app.md
In the Go documentation for the function `app.Test` it mentions it's `1s`, which is also how it is in the code, obviously.
=> Fix app.Test default test timeout mentioned

api/ctx.md
Fixed typo where it currently says `Request` when it should say `Response` as it is referring to the `Response()` func
=> Fix type for Context section in docs

api/middleware/limiter.md
Example now uses `Storage` instead of the deprecated `Store`
=> Update example for limiter storage

api/ctx.md
replaced wrong param `:name` with `:id`
=> fixed wrong param name

api/middleware/limiter.md
Related pr: https://github.com/gofiber/fiber/pull/1542
=> Update limiter middleware doc

api/fiber.md
Part of https://github.com/gofiber/fiber/pull/1560
This PR updates the docs for ErrorHandler to mention that mounted fiber error handlers are retained and use accordingly based on the prefix path.
=> Update ErrorHandler docs for mounted fibers

api/fiber.md
=> doc(fiber): correct Markdown syntax

guide/validation.md
By default, it sends the `200 OK` status code.
I've replaced it with `400 Bad Request`.
=> fix(guide): incorrect HTTP status code on validation error

api/ctx.md, api/middleware/csrf.md, original/context.md
Pending task for [this PR](https://github.com/gofiber/fiber/pull/1752)
=> Add docs for Session only cookies

api/ctx.md
Documents `ctx.RestartRouting` added with https://github.com/gofiber/fiber/pull/1739.
=> 📚 Add documentation for ctx.RestartRouting

api/middleware/limiter.md
Change mentioning of deprecated `Duration` to `Expiration`
=> Fix comment

api/app.md
https://github.com/gofiber/fiber/pull/1761
=> Add docs for mTLS and TLS updates

api/ctx.md
Doc for https://github.com/gofiber/fiber/pull/1831
=> Add doc for GetRouteURL

SUMMARY.md, api/fiber.md, guide/faster-fiber.md
related https://github.com/gofiber/fiber/pull/1851
=> Add new guide about speed, add missing config fields

extra/faq.md
Update docs as per gofiber/fiber#1847
This assumes that gofiber/fiber#1847 will be included in v2.32.0.
=> Update docs as per gofiber/fiber#1847

api/ctx.md
Add a documentation for new ctx.Writef() function.
And add a missed description for already available ctx.WriteString() function.
=> Add descriptions for ctx.Writef() and ctx.WriteString()

guide/faster-fiber.md
Small update to the link that is pointing to the `go-json` library.
=> fix: Broken link to go-json library

README.md, api/app.md, api/ctx.md, api/middleware/monitor.md, extra/faq.md, guide/error-handling.md, original/README.md, original/application.md, original/context.md, original/middleware.md
- update links
- update monitor mw docs
- overhaul main README
See also [title](https://github.com/gofiber/fiber/pull/1893) and [refresh](https://github.com/gofiber/fiber/pull/1898) for monitor mw.
=> links & monitor & README

extra/faq.md
Add missing link locations to the FAQ page.
=> Update links on the FAQ page

guide/hooks.md
Documentation at https://github.com/gofiber/fiber/pull/1974.
=> add: OnFork docs

SUMMARY.md, api/middleware.md, api/middleware/envvar.md
Related to gofiber/fiber:
https://github.com/gofiber/fiber/pull/2054
https://github.com/gofiber/fiber/issues/2053
=> add envvar middleware docs

README.md
* This PR replaces `ImmutableString` which is deprecated with `CopyString`
* Also adds an example of how to set `Immutable: true` for the Fiber app.
=> Remove mentions of deprecated functions in README

README.md
The code contains `&fiber.Settings` which should be replaced with `fiber.Config` as of v2.
=> Fixed example code in README.md

guide/routing.md
This made the constraint not be available on the website due to being interpreted as a HTML tag.
=> guide: fix escaping of "<guid>" constraint

guide/routing.md, original/routing.md
The unaware user might end up reusing the example code. Instead, users should refer to e.g. https://github.com/gofiber/helmet for security-relevant headers.
=> guide,original: do not use security headers in middleware response

api/middleware/session.md, guide/routing.md
This PR adds an example of using constraints on an optional parameter as part of gofiber/fiber#2179 and as requested in [this comment](https://github.com/gofiber/fiber/pull/2179#issuecomment-1298163921).
=> 📝Add optional parameter example to routing constraints section

api/middleware/pprof.md
Relates to: https://github.com/gofiber/fiber/pull/2194
In systems with multiple ingress endpoints all sharing the same load balancer and base URL, it is common to place servers behind a URL prefix. To facilitate this, this PR allows the pprof middleware to define a URL Prefix during configuration so that the endpoints are served on an appropriate URL.
Please delete options that are not relevant.
Use emojis on commit messages so it provides an easy way of identifying the purpose or intention of a commit. Check out the emoji cheatsheet here: https://gitmoji.carloscuesta.me/
=> Update docs to add URL prefix to pprof middleware

api/ctx.md
The main package received an update in v2.40.0 that changed a method signature but did not update the documentation to match.
https://github.com/gofiber/fiber/commit/ff4602980a2a88b4a543641714716e7a348b3007
Fixes https://github.com/gofiber/docs/issues/307
I didn't find any contributing guide, so please let me know if there's anything else y'all need. :)
=> Update method signature of `Locals()` to match latest release

api/middleware/filesystem.md
related to https://github.com/gofiber/fiber/pull/2247
=> :memo: middleware/filesystem does not handle url encoded values

docs/guide/routing.md
The "Optional Parameter Example" was duplicated.
=> Remove duplication

docs/api/middleware/filesystem.md
syncing from official repo PRs:
- [docs(filesystem): fix statik filesystem middleware example typo](https://github.com/gofiber/fiber/pull/2302)
- [docs(filesystem): clean duplicated namespace for example](https://github.com/gofiber/fiber/pull/2313)
=> 📝 docs(filesystem): fix statik filesystem middleware example typo
